[project]
name = "plots"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
    "pyqt6>=6.8.0",
    "seaborn>=0.13.2",
]
